kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-notebook-pv
  labels:
    release: stable
  namespace: spark
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data
