kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-notebook-pvc
  namespace: spark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.5Gi
  selector:
    matchLabels:
      release: stable
